filter-by-commitish: true
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'auto-update'
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'no-release'
  default: minor

categories:
  - title: 'ğŸš€ Enhancements'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: 'ğŸ“š Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'ğŸ§¹ Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'
  - title: 'ğŸ¤– Automatic Updates'
    labels:
      - 'auto-update'

change-template: |
  <details>
  <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>

  $BODY
  </details>

template: |
  $CHANGES

replacers:
  # Remove irrelevant information from Renovate bot
  - search: '/(?<=---\s)\s*^#.*(Renovate configuration|Configuration)(?:.|\\n)*?This PR has been generated .*/gm'
    replace: ''
  # Remove Renovate bot banner image
  - search: '/\[\[^\[\]]*Renovate\][^\[\]]*\](\([^)]*\))?\s*\n+/gm'
    replace: ''
