[versions]
# Kotlin
kotlin = "1.9.25"

# IntelliJ Platform
intellijPlatform = "2.3.0"

# Libraries
kotlinxCoroutines = "1.8.1"
kotlinxSerialization = "1.6.3"
snakeyaml = "2.2"

# Testing
junit = "5.10.2"
mockk = "1.13.10"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
changelog = { id = "org.jetbrains.changelog", version = "2.2.0" }

[libraries]
kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }

# Testing
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
